backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Category", name: "category", widget: "select", options: ["case-study", "marketing-tips", "industry-insights"]}
      - {label: "Summary", name: "summary", widget: "text"}
      - {label: "Read Time", name: "read_time", widget: "string"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
