/**
 * Abels Moving Services — Board Presentation Builder
 * Generated by HUDL Consultancy · 5 June 2026
 *
 * HOW TO USE IN 4 STEPS:
 * 1. Go to script.google.com → click "New project"
 * 2. Delete the placeholder code, paste this entire file
 * 3. Click the ▶ Run button (select "buildPresentation" if prompted)
 * 4. Grant Google permissions when prompted — then check the Execution Log
 *    for the link to your new presentation.
 *
 * The script creates a new Google Slides deck in your Drive,
 * fully formatted with 12 slides covering all 5 KPIs,
 * campaign activity, financial summary and Q3 roadmap.
 */

function buildPresentation() {

  // ── Create presentation ──────────────────────────────────────────────────
  var pres = SlidesApp.create('Abels Moving Services — Marketing Performance May 2026');
  var W = pres.getPageWidth();   // points (default ~720)
  var H = pres.getPageHeight();  // points (default ~405)

  // Clear the default first slide's placeholders
  var titleSlide = pres.getSlides()[0];
  titleSlide.getPageElements().forEach(function(el) { el.remove(); });

  // ── Brand colours ────────────────────────────────────────────────────────
  var C = {
    black:  '#0c0c0c',
    card:   '#111111',
    row1:   '#0d0d0d',
    white:  '#ffffff',
    yellow: '#fbbf46',
    blue:   '#45aeff',
    cyan:   '#1edfd4',
    red:    '#ff515e',
    green:  '#22c55e',
    amber:  '#f59e0b',
    muted:  '#9a9a9a',
    tblHdr: '#0a1a2a',
  };

  // ── Helpers ──────────────────────────────────────────────────────────────

  function addSlide() {
    var s = pres.appendSlide(SlidesApp.PredefinedLayout.BLANK);
    s.getPlaceholders().forEach(function(p) { p.remove(); });
    return s;
  }

  function bg(slide, hex) {
    slide.getBackground().setSolidFill(hex);
  }

  // Four-colour stripe bar across the top
  function stripe(slide) {
    var bw = W / 4;
    var colors = [C.yellow, C.blue, C.red, C.cyan];
    colors.forEach(function(c, i) {
      var r = slide.insertShape(SlidesApp.ShapeType.RECTANGLE, i * bw, 0, bw, 5);
      r.getFill().setSolidFill(c);
      r.getBorder().setTransparent();
    });
  }

  // Insert a text box with styling
  function txt(slide, text, left, top, width, height, opts) {
    var o = opts || {};
    var box = slide.insertTextBox(text, left, top, width, height);
    var ts  = box.getText().getTextStyle();
    ts.setForegroundColor(o.color  || C.white);
    ts.setFontSize(o.size          || 12);
    if (o.bold)  ts.setBold(true);
    var ps = box.getText().getParagraphStyle();
    if (o.center) ps.setParagraphAlignment(SlidesApp.ParagraphAlignment.CENTER);
    return box;
  }

  // Insert a simple rectangle (for milestone boxes, etc.)
  function rect(slide, left, top, width, height, fillHex, borderHex) {
    var r = slide.insertShape(SlidesApp.ShapeType.RECTANGLE, left, top, width, height);
    r.getFill().setSolidFill(fillHex || C.card);
    if (borderHex) { r.getBorder().setSolidFill(borderHex); }
    else           { r.getBorder().setTransparent(); }
    return r;
  }

  // Build a table with header row
  function makeTable(slide, left, top, width, height, headers, rows, opts) {
    var o = opts || {};
    var t = slide.insertTable(rows.length + 1, headers.length, left, top, width, height);

    // Header row
    headers.forEach(function(h, c) {
      var cell = t.getCell(0, c);
      cell.getText().setText(h);
      var ts = cell.getText().getTextStyle();
      ts.setForegroundColor(o.headerColor || C.blue);
      ts.setBold(true);
      ts.setFontSize(o.headerSize || 10);
      cell.getFill().setSolidFill(C.tblHdr);
    });

    // Data rows
    rows.forEach(function(row, r) {
      var rowBg = (r % 2 === 0) ? C.row1 : C.black;
      if (o.rowBg && o.rowBg[r]) rowBg = o.rowBg[r];
      row.forEach(function(cellText, c) {
        var tc = t.getCell(r + 1, c);
        tc.getText().setText(String(cellText));
        var ts = tc.getText().getTextStyle();
        ts.setFontSize(o.cellSize || 10);
        var color = C.muted;
        if (c === 0) color = C.white;
        if (o.cellColor && o.cellColor[r] && o.cellColor[r][c]) color = o.cellColor[r][c];
        ts.setForegroundColor(color);
        if (o.cellBold && o.cellBold[r] && o.cellBold[r][c]) ts.setBold(true);
        tc.getFill().setSolidFill(rowBg);
      });
    });
    return t;
  }

  // ── SLIDE 1 — Title ──────────────────────────────────────────────────────
  (function() {
    var s = titleSlide;
    bg(s, C.black);
    stripe(s);
    // Decorative accent bar left
    rect(s, 0, 0, 4, H, C.yellow);

    txt(s, 'ABELS MOVING SERVICES',
        60, 80, W - 120, 60,
        {color: C.yellow, size: 36, bold: true, center: true});

    txt(s, 'Marketing Performance — May 2026',
        60, 148, W - 120, 34,
        {color: C.white, size: 20, center: true});

    txt(s, 'Board Pack  ·  AGM Group',
        60, 186, W - 120, 24,
        {color: C.muted, size: 13, center: true});

    // Divider
    var line = s.insertShape(SlidesApp.ShapeType.RECTANGLE, 200, 218, W - 400, 1);
    line.getFill().setSolidFill(C.muted);
    line.getBorder().setTransparent();

    txt(s, 'Prepared by HUDL Consultancy\nWoody · Fractional Marketing Director\n5 June 2026',
        60, 228, W - 120, 60,
        {color: C.muted, size: 11, center: true});

    txt(s, 'CONFIDENTIAL — INTERNAL ONLY',
        60, H - 26, W - 120, 18,
        {color: '#444444', size: 9, center: true});
  })();

  // ── SLIDE 2 — Executive Summary ──────────────────────────────────────────
  (function() {
    var s = addSlide();
    bg(s, C.black);
    stripe(s);
    txt(s, 'EXECUTIVE SUMMARY', 20, 10, 340, 26, {color: C.yellow, size: 16, bold: true});

    var ragColor = {Green: C.green, Amber: C.amber, Red: C.red};
    var rows = [
      ['Website Visitors',  '2,478 active users',              'Stable vs Apr; spring softening',                  '−36.8% YoY — PMAX removed (strategic)',       'Amber'],
      ['Conversion Volume', '37 lead forms (May)',             '124 Group 2 forms Jan–May (≈24.8/mo)',             '2025: ≈49/mo — different tracking definition',  'Amber'],
      ['Conversion Quality','38.5% GM · £5,508 avg job · 21d','GM up (31.3%→38.5%); speed doubled (41→21 days)', 'Margin and speed both improving YoY',           'Green'],
      ['Cost per Lead',     '£160 blended (May)',              'Holding £160–165 since Apr after Mar spike (£228)','Genuine 2025 CPL ≈£46 — different definition',  'Green'],
      ['Spend vs Budget',   '£5,929 of ~£6,200 (96%)',        'Near-capacity since Apr (99–96%)',                  '£200/day confirmed by Neil Pertoldi',           'Green'],
    ];

    var cellColor = rows.map(function(row) {
      return [C.white, C.muted, C.muted, C.muted, ragColor[row[4]] || C.muted];
    });
    var cellBold = rows.map(function(row) {
      return [false, false, false, false, true];
    });

    makeTable(s,
      20, 42, W - 40, H - 64,
      ['KPI', 'May 2026', 'Trend (Jan–May)', 'YoY context', 'Status'],
      rows,
      {cellSize: 9, headerSize: 10, cellColor: cellColor, cellBold: cellBold}
    );

    txt(s, '▸ Single booked job (avg £5,508 · 38.5% GM) covers ~32–42 lead-form enquiries at current CPL. Europe and London are profitable but budget-throttled; Domestic is the structural outlier being fixed in Q3.',
        20, H - 20, W - 40, 16, {color: C.muted, size: 9});
  })();

  // ── SLIDES 3–7 — KPI Deep-Dives ──────────────────────────────────────────
  var kpis = [
    {
      num: '01', title: 'Website Visitors', color: C.blue,
      what: '2,478 active users · 2,847 sessions in May\n13,329 active users Jan–May\n−36.8% YoY (May 2025: 3,918)',
      why:  'Decline is strategic, not a failure. In 2025, Performance Max generated 11.4 million impressions — almost entirely low-intent display traffic with sub-1% CTR. We removed PMAX and switched to five targeted Search-only campaigns.\n\nTraffic volume is down; audience quality is up.',
      how:  '9.6% Search conversion rate proves the higher-quality audience. Three levers to recover volume:\n• Unlock Europe\'s 44% lost impression share\n• Unlock London\'s 63% lost impression share\n• Structured SEO activity\n\nBoth impression-share gaps are addressed in Q3 reallocation (7 July).'
    },
    {
      num: '02', title: 'Conversion Volume', color: C.cyan,
      what: '37 lead forms in May\n124 Group 2 form submissions Jan–May (≈24.8/mo)\n\nNOTE: Group 2 = genuine form enquiries only. 2026 counts only this.',
      why:  '2025 counted soft actions (page views, phone clicks, get-directions) as conversions — producing the misleading £21 CPA and ≈177 conv/month. In 2026 those are switched off.\n\nGenuine 2025 rate was ≈49 form subs/month vs 2026 ≈25/month. The gap reflects: −37% traffic (PMAX removed) + lower budget + Domestic structural inefficiency.',
      how:  'Europe drove 19 of May\'s 37 conversions (51%) — the clearest signal of where budget belongs.\n\nEurope and London are "budget limited" — campaigns stop serving mid-day when their daily cap is reached. 124 enquiries is a floor, not a ceiling. Q3 reallocation directly targets this constraint.'
    },
    {
      num: '03', title: 'Conversion Quality', color: C.green,
      what: '53 jobs won · £291,919 won revenue · Jan–May 2026\n38.5% gross margin (up from 31.3% in 2025)\n£5,508 average won job value\n21 average days to book (down from 41 in 2025)\n\nSource: AGM Power BI · all channels, not paid media only.',
      why:  'The commercial proof point: enquiries are converting into higher-margin jobs, faster. Gross margin improved materially (31.3%→38.5%). Deals close in half the time (41→21 days). Average job value is steady at ~£5,500 — no evidence of trading down.\n\nThe business is winning better jobs, not just more jobs.',
      how:  'Commercial framing: £130–170 CPL against £5,508 avg won job at 38.5% GM (~£2,120 gross profit) = each booked job covers 12–16 lead-form enquiries at cost.\n\nRouting budget toward Europe and London — lowest CPL, highest win rate — is the lever to lift monthly won revenue without touching margin.'
    },
    {
      num: '04', title: 'Cost per Lead (CPL)', color: C.yellow,
      what: '£160 blended (May)\n£165 blended Jan–May\n\nBy campaign (Jan–May):\nEurope £130 · London £151 · International £174\nDomestic £299 · Brand £24',
      why:  '£165 blended CPL is commercially sound — see KPI 3.\n\nDomestic is the structural outlier: £299/enquiry against a £165 blended average, and the only campaign returning less value than it costs (0.74×). Root cause: irrelevant query triggering — man-and-van, self-storage, recruitment searches diluting conversion rate.',
      how:  'Domestic Clean-Up Pack (live 23 June):\n• 90 negative keywords across waste categories\n• Core terms migrated from broad → phrase/exact match\n• tCPA target recalibrated\n\nTarget: £200–230 CPA from £299 over 6–8 weeks.\nQ3 reallocation channels freed budget into Europe and London where each pound works hardest.'
    },
    {
      num: '05', title: 'Spend vs Budget', color: C.cyan,
      what: 'May 2026 Search: £5,929 (of ~£6,200 ceiling = 96%)\nJan–May 2026 Search total: £22,364\nMonthly trend: Jan £3,751 · Feb £1,339 · Mar £5,242 · Apr £6,103 · May £5,929\n\nBudget ceiling: £200/day confirmed by Neil Pertoldi.',
      why:  'The account is running at effective capacity in Apr–May (99–96% utilisation). The goal is not to spend as much as possible, but to spend in the places that generate the most profitable enquiries.\n\n£200/day total is held in Q3 — the reallocation changes the distribution, not the total.',
      how:  'Q3 reallocation (go-live 7 July):\nEurope: £97 → £115–130/day\nLondon: £28 → £45–55/day\nDomestic: £40 → £20/day\nInternational + Brand: unchanged\n\nPhased: Domestic clean-up 23 Jun → budget shift 7 Jul → tCPA calibration 14 Jul.\nSmart Bidding needs 2–4 weeks to recalibrate after each change.'
    },
  ];

  kpis.forEach(function(kpi) {
    var s = addSlide();
    bg(s, C.black);
    stripe(s);

    // Badge + title
    var badge = s.insertShape(SlidesApp.ShapeType.ROUND_RECTANGLE, 20, 10, 56, 22);
    badge.getFill().setSolidFill(kpi.color);
    badge.getBorder().setTransparent();
    txt(s, 'KPI ' + kpi.num, 20, 10, 56, 22, {color: C.black, size: 10, bold: true, center: true});
    txt(s, kpi.title.toUpperCase(), 84, 10, W - 104, 22, {color: C.white, size: 16, bold: true});

    // Three-column layout
    var colW  = (W - 50) / 3;
    var col2x = 20 + colW + 5;
    var col3x = 20 + colW * 2 + 10;
    var labelY = 38, colY = 56, colH = H - colY - 16;

    // Label headers
    [['WHAT', 20], ['WHY', col2x], ['HOW', col3x]].forEach(function(pair) {
      txt(s, pair[0], pair[1], labelY, colW, 14, {color: kpi.color, size: 9, bold: true});
    });

    // Content boxes
    function col(text, x) {
      var box = s.insertTextBox(text, x, colY, colW, colH);
      box.getText().getTextStyle().setForegroundColor(C.muted).setFontSize(10);
      box.getFill().setSolidFill(C.row1);
    }
    col(kpi.what, 20);
    col(kpi.why, col2x);
    col(kpi.how, col3x);
  });

  // ── SLIDE 8 — Campaign Activity ──────────────────────────────────────────
  (function() {
    var s = addSlide();
    bg(s, C.black);
    stripe(s);
    txt(s, 'CAMPAIGN ACTIVITY — MAY / JUNE 2026', 20, 10, W - 40, 24, {color: C.yellow, size: 14, bold: true});

    var statusColors = {Completed: C.green, Prepared: C.amber, Recommended: C.blue};
    var rows = [
      ['Account audit & diagnosis',          'Full campaign review — identified Domestic over-funded, Europe/London under-funded', 'Completed',   'Pippa',          'Done'],
      ['Domestic clean-up pack',             '90 negatives + match-type tightening · target CPA £200–230 from £299',              'Prepared',    'Pippa',          '23 Jun'],
      ['Budget reallocation',               'Europe ↑ London ↑ Domestic ↓ · total held at £200/day',                             'Prepared',    'Pippa',          '7 Jul'],
      ['Q3 brief + RSA ad copy',            '15 headlines + 4 descriptions per campaign + Europe & London landing pages',         'Completed',   'Hunter / Otis',  'Sign-off needed'],
      ['GA4 analytics review',              'Dashboard updated; quote-path UX opportunity flagged (4.1% key-event rate)',         'Completed',   'Dash',           'Done'],
      ['Conversion tracking reconciliation','Proved 2025 counted soft actions; 2026 counts form submits only',                    'Completed',   'Pippa',          'Done'],
      ['Offline conversion import',         'Re-enable Moveware→Google Ads (88 qualified leads / £44k in 2025 — 0 in 2026)',     'Recommended', 'Woody + JDR',    'Q3'],
    ];

    var cellColor = rows.map(function(row) {
      return [C.white, C.muted, statusColors[row[2]] || C.muted, C.muted, C.muted];
    });
    var cellBold = rows.map(function(row) {
      return [true, false, true, false, false];
    });

    makeTable(s,
      20, 40, W - 40, H - 56,
      ['Initiative', 'What', 'Status', 'Owner', 'Live'],
      rows,
      {cellSize: 9, headerSize: 10, cellColor: cellColor, cellBold: cellBold}
    );
  })();

  // ── SLIDE 9 — Financial: Monthly Spend ───────────────────────────────────
  (function() {
    var s = addSlide();
    bg(s, C.black);
    stripe(s);
    txt(s, 'FINANCIAL SUMMARY — MONTHLY SPEND JAN–MAY 2026', 20, 10, W - 40, 24, {color: C.yellow, size: 14, bold: true});

    var rows = [
      ['January 2026',  '£3,751', '29', '£130', '~£6,200', '61%'],
      ['February 2026', '£1,339', '9',  '£149', '~£5,600', '24%'],
      ['March 2026',    '£5,242', '23', '£228', '~£6,200', '85%'],
      ['April 2026',    '£6,103', '38', '£161', '~£6,000', '102%'],
      ['May 2026',      '£5,929', '37', '£160', '~£6,200', '96%'],
      ['Jan–May total', '£22,364','136', '£165 blended', '£200/day confirmed', '—'],
    ];

    var rowBg  = {4: '#0a1a25', 5: '#1a1500'};
    var cellColor = rows.map(function(row, r) {
      if (r === 4) return [C.cyan, C.cyan, C.cyan, C.cyan, C.cyan, C.cyan];
      if (r === 5) return [C.yellow, C.yellow, C.yellow, C.yellow, C.yellow, C.yellow];
      return [C.white, C.muted, C.muted, C.muted, C.muted, C.muted];
    });
    var cellBold = rows.map(function(row, r) {
      return [false, r >= 4, r >= 4, r >= 4, r >= 4, r >= 4];
    });

    makeTable(s,
      20, 40, W - 40, H - 80,
      ['Month', 'Search Spend', 'Conversions', 'CPA', 'Budget Ceiling', 'Utilisation'],
      rows,
      {cellSize: 11, headerSize: 11, rowBg: rowBg, cellColor: cellColor, cellBold: cellBold}
    );

    txt(s, '* April 102% is within daily budget pacing tolerance. Feb reflects early-year campaign calibration period.',
        20, H - 34, W - 40, 14, {color: '#555555', size: 9});
    txt(s, 'Budget ceiling £200/day confirmed by Neil Pertoldi. Total Search (all campaigns): £22,364. JDR-managed campaigns: £16,432.',
        20, H - 20, W - 40, 14, {color: C.muted, size: 9});
  })();

  // ── SLIDE 10 — Financial: CPA by Campaign ────────────────────────────────
  (function() {
    var s = addSlide();
    bg(s, C.black);
    stripe(s);
    txt(s, 'CPA BY CAMPAIGN — JAN–MAY 2026 (JDR Search)', 20, 10, W - 40, 24, {color: C.yellow, size: 14, bold: true});

    var campColors = {
      'Europe (Outbound)': C.green,
      'London':            C.cyan,
      'International':     C.blue,
      'Brand':             C.muted,
      'Domestic':          C.red,
      'Blended (Search)':  C.yellow,
    };

    var rows = [
      ['Europe (Outbound)', '£6,119', '46.89', '£130', '2.57×', '44.4%', 'Best in account'],
      ['London',            '£2,872', '19.00', '£151', '1.83×', '62.9%', 'Strong — most throttled'],
      ['International',     '£1,391', '8.00',  '£174', '2.03×', '36.5%', 'Efficient — small sample'],
      ['Brand',             '£72',    '3.00',  '£24',  '5.63×', '2.1%',  'Exceptional'],
      ['Domestic',          '£5,979', '20.00', '£299', '0.74×', '22.4%', '⚠ Requires attention'],
      ['Blended (Search)',  '£16,432','96.89', '£170', '1.74×', '—',     'Within target range'],
    ];

    var cellColor = rows.map(function(row) {
      return [campColors[row[0]] || C.white, C.muted, C.muted, C.muted, C.muted, C.muted, C.muted];
    });
    cellColor[4] = [C.red, C.red, C.red, C.red, C.red, C.red, C.red]; // Domestic row
    cellColor[5] = [C.yellow, C.yellow, C.yellow, C.yellow, C.yellow, C.yellow, C.yellow]; // Total row

    var cellBold = rows.map(function(row, r) {
      return [true, false, false, false, false, false, false];
    });

    var rowBg = {4: '#1a0808', 5: '#1a1500'};

    makeTable(s,
      20, 40, W - 40, H - 100,
      ['Campaign', 'Spend', 'Conv.', 'CPA', 'Value/Cost', 'Lost IS Budget', 'Note'],
      rows,
      {cellSize: 10, headerSize: 10, rowBg: rowBg, cellColor: cellColor, cellBold: cellBold}
    );

    // May breakdown sub-table
    txt(s, 'MAY 2026 BREAKDOWN', 20, H - 52, 200, 14, {color: C.muted, size: 9, bold: true});
    var may = [['Europe £2,431 · 19 conv · £128', 'London £829 · 6 conv · £138', 'Domestic £1,196 · 6 conv · £199', 'International £912 · 5 conv · £182']];
    txt(s, 'Europe £2,431 · 19 conv · £128      London £829 · 6 conv · £138      Domestic £1,196 · 6 conv · £199      International £912 · 5 conv · £182      Brand £49 · 1 conv · £49',
        20, H - 36, W - 40, 30, {color: C.muted, size: 9});
  })();

  // ── SLIDE 11 — Q3 Roadmap ────────────────────────────────────────────────
  (function() {
    var s = addSlide();
    bg(s, C.black);
    stripe(s);
    txt(s, 'Q3 ROADMAP', 20, 10, 250, 24, {color: C.yellow, size: 16, bold: true});
    txt(s, 'Total daily budget held at £200/day throughout', W - 310, 12, 290, 18, {color: C.muted, size: 10});

    // Milestone boxes
    var milestones = [
      {date: '23 Jun', label: 'Domestic clean-up live', note: 'Negatives + match-type tightening', color: C.cyan},
      {date: '7 Jul',  label: 'Budget reallocation',    note: 'Europe ↑ · London ↑ · Domestic ↓', color: C.yellow},
      {date: '14 Jul', label: 'Domestic tCPA set',      note: 'After clean-up and budgets settle',  color: C.blue},
    ];

    var mw = (W - 50) / 3;
    milestones.forEach(function(m, i) {
      var x = 20 + i * (mw + 5);
      var box = s.insertShape(SlidesApp.ShapeType.RECTANGLE, x, 42, mw, 68);
      box.getFill().setSolidFill(C.card);
      box.getBorder().setSolidFill(m.color);
      txt(s, m.date,  x + 8, 46,  mw - 16, 18, {color: m.color, size: 13, bold: true});
      txt(s, m.label, x + 8, 66,  mw - 16, 18, {color: C.white, size: 11, bold: true});
      txt(s, m.note,  x + 8, 84,  mw - 16, 18, {color: C.muted, size: 10});
    });

    txt(s, 'Smart Bidding needs 2–4 weeks to recalibrate after each change — changes are staggered deliberately.',
        20, 114, W - 40, 14, {color: '#555555', size: 9});

    // Targets table
    txt(s, 'Q3 TARGETS', 20, 134, 200, 16, {color: C.muted, size: 9, bold: true});
    makeTable(s,
      20, 152, (W - 40) / 2, H - 172 - 30,
      ['Metric', 'Current', 'Q3 Target'],
      [
        ['Domestic CPA',          '£299',   '£200–230'],
        ['Blended CPA',           '£165',   '≤ £170 (hold)'],
        ['Europe lost IS budget', '44.4%',  '< 20%'],
        ['London lost IS budget', '62.9%',  '< 25%'],
      ],
      {cellSize: 10, headerSize: 10,
       cellColor: [
         [C.white, C.red, C.green],
         [C.white, C.muted, C.cyan],
         [C.white, C.muted, C.cyan],
         [C.white, C.muted, C.cyan],
       ]}
    );

    // Outstanding action
    txt(s, 'OUTSTANDING ACTION', W/2 + 10, 134, W/2 - 30, 16, {color: C.muted, size: 9, bold: true});
    var actBox = s.insertShape(SlidesApp.ShapeType.RECTANGLE, W/2 + 10, 152, W/2 - 30, H - 172 - 30);
    actBox.getFill().setSolidFill('#0a1020');
    actBox.getBorder().setSolidFill(C.blue);
    txt(s, 'Re-enable Moveware → Google Ads offline conversion import',
        W/2 + 18, 158, W/2 - 46, 22, {color: C.blue, size: 11, bold: true});
    txt(s, '2025: 88 qualified leads imported → Smart Bidding optimised toward booked revenue\n2026: 0 imported → algorithm optimises toward form fills only\n\nAction: Woody + JDR (upload schedule) + NetDesigner (GCLID capture)\nImpact: Smart Bidding optimises toward revenue, not just enquiries',
        W/2 + 18, 180, W/2 - 46, H - 200 - 30, {color: C.muted, size: 10});

    txt(s, 'Internal — not for external distribution · HUDL Consultancy · woody@hudl.gg',
        20, H - 22, W - 40, 14, {color: '#333333', size: 8, center: true});
  })();

  // ── SLIDE 12 — Next Steps ────────────────────────────────────────────────
  (function() {
    var s = addSlide();
    bg(s, C.black);
    stripe(s);
    txt(s, 'NEXT STEPS', 20, 10, 300, 24, {color: C.yellow, size: 18, bold: true});

    var steps = [
      {label: 'Sign off Q3 brief & ad copy',            note: 'Europe, London, Domestic RSAs + landing pages ready — needed before 7 July go-live',     color: C.cyan,   owner: 'Woody → sign off'},
      {label: 'Domestic clean-up: 23 June',             note: 'JDR to implement 90 negatives + match-type changes in the Google Ads account',             color: C.yellow, owner: 'JDR Group'},
      {label: 'Budget reallocation: 7 July',            note: 'Europe & London budgets increased; Domestic reduced — total £200/day held',                color: C.yellow, owner: 'JDR Group'},
      {label: 'Re-enable Moveware offline import',      note: 'Upgrades Smart Bidding from form-fills to revenue optimisation (2025: 88 leads, £44k)',    color: C.blue,   owner: 'Woody + JDR + NetDesigner'},
      {label: 'June 2026 board report',                 note: 'First full month with reallocation active — expected improvement in CPL and lead volume', color: C.muted,  owner: 'HUDL (Pippa) — July'},
    ];

    steps.forEach(function(step, i) {
      var y = 42 + i * 52;
      var box = s.insertShape(SlidesApp.ShapeType.RECTANGLE, 20, y, W - 40, 46);
      box.getFill().setSolidFill(C.row1);
      box.getBorder().setTransparent();
      // Accent strip
      var accent = s.insertShape(SlidesApp.ShapeType.RECTANGLE, 20, y, 3, 46);
      accent.getFill().setSolidFill(step.color);
      accent.getBorder().setTransparent();
      txt(s, step.label, 30, y + 4,  W - 180, 18, {color: C.white, size: 12, bold: true});
      txt(s, step.note,  30, y + 22, W - 180, 18, {color: C.muted, size: 10});
      txt(s, step.owner, W - 155, y + 10, 130, 22, {color: step.color, size: 10, bold: true, center: true});
    });

    txt(s, 'HUDL Consultancy · Woody · woody@hudl.gg · Internal — not for external distribution',
        20, H - 22, W - 40, 14, {color: '#333333', size: 8, center: true});
  })();

  // ── Done ─────────────────────────────────────────────────────────────────
  var url = pres.getUrl();
  Logger.log('');
  Logger.log('✅  Presentation created successfully!');
  Logger.log('🔗  Open it here: ' + url);
  Logger.log('📋  ID: ' + pres.getId());
  Logger.log('');
  Logger.log('12 slides · Abels Moving Services · May 2026 Board Pack');
}
